#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter()
{
    _fileName = "NoName.html";

    _fontName = "굴림";
    _fontSize = 3;
    _fontColor = "black";
}

HTMLWriter::~HTMLWriter() { }

void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor)
{
    _fontName = fontName;
    _fontSize = fontSize;
    _fontColor = fontColor;
}

void HTMLWriter::Write()
{
    ofstream of(_fileName.c_str());

    of << "<html><hear><title>This document was generated by HTMLWriter</title></head><body>";
    of << "<h1>Content</h1>";

    of << "<font name = " << _fontName << "'size = '" << _fontSize << "' color = '" << _fontColor << ">";

    of << _content;
    of << "</font>";
    of << "</body></html>";
}